### ISSUE TITLE
How to deploy using docker-compose but without https?

### ISSUE THREAD

**Issue by arladmin** [h-mdm/hmdm-docker#17]
I could not find any option to disable https when deploying with docker-compose.

How to do it?

**Comment by h-mdm** [comment]
You can set the PROTOCOL variable to http (it defaults to https). 

Please note that this option hasn't been tested and is not recommended for production usage.

**Comment by arladmin** [comment]
@h-mdm just tried that.
The container is still deploying with the environmental variables set to:
```
HTTPS_LETSENCRYPT: true
PROTOCOL: true
```

Basically, the default image `headwindmdm/hmdm:0.1.2` is overriding my variables.

**Comment by arladmin** [comment]
The logs are stuck on:
```
Keys not found, waiting...
```

**Comment by arladmin** [comment]
My `docker-compose.yml` :

```
version: '3'

services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes: 
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    image: headwindmdm/hmdm:0.1.2
    ports:
      - 31000:31000
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
```

My `.env` : 

```
SQL_BASE=hmdm
SQL_USER=hmdm
SQL_PASS=<PASS>
ADMIN_EMAIL=<email>
BASE_DOMAIN=<domain>
HMDM_VARIANT=os
DOWNLOAD_CREDENTIALS=
HMDM_URL=https://h-mdm.com/files/hmdm-5.12.1-os.war
CLIENT_VERSION=5.14
PROTOCOL=http
HTTPS_LETSENCRYPT=false
```

But, after deploying, the `PROTOCOL` variable automatically becomes `true`.

<hr>

Even tried with `FORCE_RECONFIGURE=true` (although, don't really know what that's supposed to do)

**Comment by h-mdm** [comment]
Sounds like a bug.

Try adding in the docker-compose.yaml (environment section):
PROTOCOL: ${PROTOCOL}

If this helps, please let me know and I will fix the script.

**Comment by arladmin** [comment]
@h-mdm Sorry, my bad. As i'm deploying via Portainer, some more config was required.

The `hmdm` container is now up, but not playing nice with the reverse proxy, it seems.

Logs:

```
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
14-Sep-2023 05:52:17.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.40
14-Sep-2023 05:52:17.848 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Nov 12 2020 15:35:02 UTC
14-Sep-2023 05:52:17.849 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.40.0
14-Sep-2023 05:52:17.849 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
14-Sep-2023 05:52:17.849 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.0-79-generic
14-Sep-2023 05:52:17.849 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
14-Sep-2023 05:52:17.849 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
14-Sep-2023 05:52:17.850 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.9.1+1
14-Sep-2023 05:52:17.850 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
14-Sep-2023 05:52:17.850 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
14-Sep-2023 05:52:17.850 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
14-Sep-2023 05:52:17.861 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
14-Sep-2023 05:52:17.861 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
14-Sep-2023 05:52:17.862 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
14-Sep-2023 05:52:17.863 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
14-Sep-2023 05:52:17.863 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
14-Sep-2023 05:52:17.863 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
14-Sep-2023 05:52:17.863 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
14-Sep-2023 05:52:17.869 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.5].
14-Sep-2023 05:52:17.870 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
14-Sep-2023 05:52:17.870 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
14-Sep-2023 05:52:17.874 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
14-Sep-2023 05:52:18.192 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
14-Sep-2023 05:52:18.225 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio-8443"]
14-Sep-2023 05:52:18.266 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[HTTP/1.1-8443]]
	org.apache.catalina.LifecycleException: Protocol handler initialization failed
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1042)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1057)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:724)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:746)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:472)
	Caused by: java.lang.IllegalArgumentException: /usr/local/tomcat/ssl/hmdm.jks (No such file or directory)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
		at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:216)
		at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141)
		at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1154)
		at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:592)
		at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:80)
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1039)
		... 13 more
	Caused by: java.io.FileNotFoundException: /usr/local/tomcat/ssl/hmdm.jks (No such file or directory)
		at java.base/java.io.FileInputStream.open0(Native Method)
		at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
		at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
		at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
		at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
		at org.apache.catalina.startup.CatalinaBaseConfigurationSource.getResource(CatalinaBaseConfigurationSource.java:121)
		at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:197)
		at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:207)
		at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.java:282)
		at org.apache.tomcat.util.net.openssl.OpenSSLUtil.getKeyManagers(OpenSSLUtil.java:98)
		at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97)
		... 20 more
14-Sep-2023 05:52:18.268 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [662] milliseconds
14-Sep-2023 05:52:18.322 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
14-Sep-2023 05:52:18.322 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.40]
14-Sep-2023 05:52:18.330 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml]
14-Sep-2023 05:52:20.977 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[HMDM-LOGGING] : Using log4j configuration from: file:///usr/local/tomcat/work/log4j-hmdm.xml
2023-09-14 05:52:22 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:22 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:22 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:22 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock
2023-09-14 05:52:23 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2023-09-14 05:52:23 [INFO] liquibase.lockservice.StandardLockService : Successfully acquired change log lock
2023-09-14 05:52:24 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2023-09-14 05:52:24 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangelog
2023-09-14 05:52:24 [INFO] liquibase.changelog.StandardChangeLogHistoryService : Reading from public.databasechangelog
2023-09-14 05:52:24 [INFO] liquibase.executor.jvm.JdbcExecutor : SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2023-09-14 05:52:24 [INFO] liquibase.lockservice.StandardLockService : Successfully released change log lock
2023-09-14 05:52:24 [INFO] com.hmdm.persistence.ConfigurationDAO : Base URL: http://mdm.tools.appl-intra.net
[HMDM-INITIALIZER]: Application initialization was successful
[HMDM-INITIALIZER]: The signal file for application initialization completion already exists: /usr/local/tomcat/work
2023-09-14 05:52:24 [INFO] org.apache.activemq.broker.BrokerService : Using Persistence Adapter: MemoryPersistenceAdapter
2023-09-14 05:52:25 [INFO] org.apache.activemq.broker.BrokerService : Apache ActiveMQ 5.15.11 (localhost, ID:73b0740c40d3-37469-1694670744921-0:1) is starting
2023-09-14 05:52:25 [INFO] org.apache.activemq.transport.TransportServerThreadSupport : Listening for connections at: mqtt://73b0740c40d3:31000
2023-09-14 05:52:25 [INFO] org.apache.activemq.broker.TransportConnector : Connector mqtt://73b0740c40d3:31000 started
2023-09-14 05:52:25 [INFO] org.apache.activemq.broker.BrokerService : Apache ActiveMQ 5.15.11 (localhost, ID:73b0740c40d3-37469-1694670744921-0:1) started
2023-09-14 05:52:25 [INFO] org.apache.activemq.broker.BrokerService : For help or more information please see: http://activemq.apache.org
2023-09-14 05:52:25 [INFO] com.hmdm.notification.guice.module.NotificationMqttTaskModule : MQTT notification service started at 0.0.0.0:31000
14-Sep-2023 05:52:25.478 INFO [main] nonapi.io.github.classgraph.classloaderhandler.lifecycle.ServletLifeCycleListener.contextInitialized Servlet context initialized
2023-09-14 05:52:26 [INFO] org.reflections.Reflections : Reflections took 83 ms to scan 11 urls, producing 390 keys and 853 values 
14-Sep-2023 05:52:27.171 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml] has finished in [8,839] ms
14-Sep-2023 05:52:27.175 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
14-Sep-2023 05:52:27.185 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [8916] milliseconds
2023-09-14 05:52:56 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Exception occurred processing: 
MQTTFrame { type: CONNACK, qos: AT_MOST_ONCE, dup:false }: org.apache.activemq.transport.mqtt.MQTTProtocolException: Unknown MQTTFrame type: 2
2023-09-14 05:52:57 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 17263 received
2023-09-14 05:52:57 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 8259 received
2023-09-14 05:52:57 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 26991 received
2023-09-14 05:52:57 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://<my-pc-ip>:63401 failed: java.net.SocketException: Connection reset
2023-09-14 05:52:58 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 17263 received
2023-09-14 05:52:58 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 8259 received
2023-09-14 05:52:58 [WARN] org.apache.activemq.transport.mqtt.MQTTProtocolConverter : Unknown PUBREL: 26991 received
2023-09-14 05:52:58 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://<my-pc-ip>:63404 failed: java.net.SocketException: Connection reset
2023-09-14 05:53:03 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://<proxy manager container ip>:37790 failed: java.net.ProtocolException: Invalid message encoding
2023-09-14 05:53:26 [WARN] org.apache.activemq.broker.TransportConnection.Transport : Transport Connection to: tcp://<my-pc-ip>:63389 failed: org.apache.activemq.transport.InactivityIOException: CONNECT frame not received with in connectionTimeout (>30000): tcp://<my-pc-ip>:63389
```

**Comment by h-mdm** [comment]
HTTPS protocol fails to initialize because you selected HTTP as the preferred protocol. This issue should not affect HTTP socket. You can see the log message: 14-Sep-2023 05:52:27.175 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]

**Comment by arladmin** [comment]
> HTTPS protocol fails to initialize because you selected HTTP as the preferred protocol.

Because the https part is being handled by nginx, outside hmdm.

<hr>

So, what's a fix for this?

Currently, the web ui doesn't work at all.

**Comment by h-mdm** [comment]
The issue is related to the interaction of your reverse proxy and Headwind MDM, so it is not related to Headwind MDM. You can test Headwind MDM UI on port 8080 (default Tomcat port). The initial issue (how to use HTTP instead of HTTPS) has been resolved.

If you want to get help on setting up a free trial of Headwind MDM Premium, please contact the technical support: https://h-mdm.com/contact-us/  We do not provide any support services for the free Community version, thank you for understanding.

**Comment by arladmin** [comment]
Well, if you consider this issue to be resolved, could you please at least provide links to detailed documentation regarding the web-server/reverse proxy handling aspects?

Because, the issue has not been resolved on my end.
**Neither `http` nor `https` is working.**

**Comment by arladmin** [comment]
Additionally, even after following the structure mentioned in the Dockerfile:
https://github.com/h-mdm/hmdm-docker/blob/master/Dockerfile, the app is not working properly.

Have now also set:
```

  hmdm:
    image: headwindmdm/hmdm:0.1.2
    ports:
      - 8443:8443
      - 8180:8080
      - 31000:31000
    env_file:
      - stack.env
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
#      - ./volumes/letsencrypt:/etc/letsencrypt
      - /path-to-external-certificates:/cert:ro
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: ${HMDM_URL}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
      PROTOCOL: ${PROTOCOL}
      HTTPS_CERT_PATH: ${HTTPS_CERT_PATH}
      HTTPS_CERT: ${HTTPS_CERT}
      HTTPS_FULLCHAIN: ${HTTPS_FULLCHAIN}
      HTTPS_PRIVKEY: ${HTTPS_PRIVKEY}
```

```
PROTOCOL=https
HTTPS_LETSENCRYPT=false
HTTPS_CERT_PATH=/cert
HTTPS_CERT=cert.pem
HTTPS_FULLCHAIN=fullchain.pem
HTTPS_PRIVKEY=privkey.pem
```

**Comment by yasiralijaved** [comment]
@arladmin Were you able to resolve it? I am too facing this issue.

**Comment by falko189** [comment]
In case somebody comes here again, the issue is docker-compose doesn't have port 8080 exposed, by adding that you will be able to proxy it on nginx 👍🏻
